name: magma agw docker build

on: [push]

jobs:
  magma-agw-docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - run: |
        git clone -b arm-agw-docker-build-fix https://github.com/ShubhamTatvamasi/magma.git --depth 1
        cd magma/lte/gateway/docker/
        docker-compose build

        MAGMA_TAG=$(git rev-parse --short HEAD)

        docker tag agw_gateway_python shubhamtatvamasi/agw_gateway_python:${MAGMA_TAG}
        docker tag agw_gateway_c shubhamtatvamasi/agw_gateway_c:${MAGMA_TAG}

        docker push shubhamtatvamasi/agw_gateway_python:${MAGMA_TAG}
        docker push shubhamtatvamasi/agw_gateway_c:${MAGMA_TAG}
